### ISSUE TITLE
After updated to newest version of kantu extension, click on xpath doesn't work anymore

### ISSUE THREAD

**Issue by Jaywinchester** [A9T9/RPA#52]
After updating to the newest version of kantu extension, previously working click command on a xpath doesn't work anymore. 

Why is this so?

**Comment by A9T9** [comment]
Do you have an example of this issue for me?

Once we can recreate it, we can fix it and release a new update asap.

**Comment by Jaywinchester** [comment]
For example the click command on this 2 css element: 
css=#appRoot > div.Files.has-footer.Files-has-leftNav.is-active > div.Files-belowHeader.Files-belowHeader--flexbox > div.od-Files-belowBar > main > div > div > div > div > div.StandaloneList-listView > div > div > div > div > div > div > div:nth-child(2) > div > div > div > div > div > div:nth-child(1) > div > div > div.ms-DetailsRow-fields.fields_9da43265 > div.ms-DetailsRow-cell.cell_9da43265.od-DetailsRow-cell--Name.isRowHeader_9da43265 > div > span > div:nth-child(2) > button > i 

and 

css=#appRoot > div.od-Files-hostContainer > div > div > div > div > div > div > div > div > div > ul > li:nth-child(5) > button > div > span

 was working before. But after the update, i can detect the elements, but the it just doesnt click on them.

**Comment by A9T9** [comment]
Do you have a complete macro for me that I can run and test? If the website or data is sensitive, you can also email it directly to team AT a9t9.com - just mention this ticket.

**Comment by A9T9** [comment]
Fixed with V2.7.3

The reason for this is that [click ](https://a9t9.com/kantu/docs/webextensions/selenium-ide/click)and similar commands now wait for the element to appear and become visible (see #34 ). In most cases this is the right thing to do, but not always. 

You can disable this with the [waitForVisible ](https://a9t9.com/kantu/docs/webextensions#!waitforvisible) internal variable.
